name: Batch

on:
  schedule:
    - cron: 0 19 * * *

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run fetch
        run: |
          deno task fetch
      
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "batch"
          git config --global user.email "m@jgs.me"
          git remote set-url origin https://e-jigsaw:${GITHUB_TOKEN}@github.com/e-jigsaw/s6x-data.git
          git checkout main
          git status
          git add .
          git commit -m 'Update'
          git push origin HEAD
