name: dispatch

on: workflow_dispatch

jobs:
  batch:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run fetch
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SECRET: ${{ secrets.SUPABASE_SECRET }}
        run: |
          deno task fetch
          deno task fetch_pages
          deno task sync
          deno task write_last

      - name: git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "batch"
          git config --global user.email "m@jgs.me"
          git remote set-url origin https://e-jigsaw:${GITHUB_TOKEN}@github.com/e-jigsaw/s6x-data.git
          git checkout main
          git status
          git add .
          git commit -m 'Update'
          git push origin HEAD
